dows:
  log:
    cdc: enable
    actLogScan: false
    applications:
      hengli:
        actlog: shdy:hengli:actlog
        binlog: shdy:hengli:biglog
      wes:
        actlog: shdy:wes:actlog
        binlog: shdy:wes:biglog