#log:
log:
  binlog:
    hosts:
      - name: wes_all
        host: 192.168.111.103
        port: 13306
        username: root
        password: shdy123!
        timeOffset: 1000
        filter:
          # 全部填 *，指定某个数据库所有表填写 db_name.*
          includes:
          #  - dows.log_ddl_demo
          # 不做排除 填写空 "" ,excludes 规则优先级高于 includes
          excludes:
          #  - dows.log_ddl_demo

  filelog:
    filter:


  auditlog:

